---
ci:
  autoupdate_schedule: quarterly
repos:
  - repo: local
    hooks:
      - id: check
        name: changelog validate
        language: python
        entry: changelogmanager --error-format github validate
        additional_dependencies:
          - "."
        pass_filenames: false
        always_run: true
