"""Regression tests for the bug where ``--bump-versions`` rewrote installed packages.

The reported failure: ``kaclm release --override-version 0.8.2 --bump-versions``
walked into ``.venv/Lib/site-packages/`` and a ``.uv-cache/`` inside the project
directory and rewrote ``__version__`` in a dozen third-party packages, taking the
test suite down and re-seeding the corruption into every rebuilt virtualenv.

Every path here stays inside ``tmp_path`` per the repo's isolate_cwd rule.
"""

from __future__ import annotations

import pytest

from changelogmanager import version_bumper
from changelogmanager.vendor import jiggle_version
from changelogmanager.vendor.jiggle_version import update

# A generated version module, verbatim in shape from a setuptools-scm install.
GENERATED_VERSION_MODULE = (
    "# file generated by setuptools-scm\n"
    "# don't change, don't track in version control\n"
    "__version__ = version = '9.1.1'\n"
    "__version_tuple__ = version_tuple = (9, 1, 1)\n"
)


def make_project(root):
    """A minimal project whose own package should be bumped."""
    (root / "pyproject.toml").write_text('[project]\nname = "demo"\nversion = "0.1.0"\n', encoding="utf-8")
    pkg = root / "demo"
    pkg.mkdir()
    (pkg / "__init__.py").write_text("__version__ = '0.1.0'\n", encoding="utf-8")
    return pkg


def make_site_packages(venv_root, *, with_pyvenv_cfg=True):
    """A virtualenv holding one installed third-party package."""
    venv_root.mkdir(parents=True, exist_ok=True)
    if with_pyvenv_cfg:
        (venv_root / "pyvenv.cfg").write_text("home = /usr\n", encoding="utf-8")
    site = venv_root / "Lib" / "site-packages" / "_pytest"
    site.mkdir(parents=True)
    victim = site / "_version.py"
    victim.write_text(GENERATED_VERSION_MODULE, encoding="utf-8")
    return victim


@pytest.mark.parametrize("venv_name", [".venv", ".venv315rc2", "venv", "env"])
def test_bump_never_descends_into_a_virtualenv(tmp_path, venv_name):
    """Named or not, a dir with a pyvenv.cfg is off limits."""
    pkg = make_project(tmp_path)
    victim = make_site_packages(tmp_path / venv_name)

    version_bumper.bump_version_files("0.8.2", project_root=tmp_path)

    assert victim.read_text(encoding="utf-8") == GENERATED_VERSION_MODULE
    assert "__version__ = '0.8.2'" in (pkg / "__init__.py").read_text("utf-8")


def test_bump_never_descends_into_site_packages_without_a_venv_marker(tmp_path):
    """site-packages is excluded by name, even with no pyvenv.cfg above it."""
    make_project(tmp_path)
    victim = make_site_packages(tmp_path / "weird_env", with_pyvenv_cfg=False)

    version_bumper.bump_version_files("0.8.2", project_root=tmp_path)

    assert victim.read_text(encoding="utf-8") == GENERATED_VERSION_MODULE


@pytest.mark.parametrize("cache_name", [".uv-cache", ".uv", ".cache", "node_modules"])
def test_bump_never_descends_into_a_package_cache(tmp_path, cache_name):
    """Corrupting a cache re-seeds every environment built from it afterwards."""
    make_project(tmp_path)
    cached = tmp_path / cache_name / "archive-v0" / "abc123" / "iniconfig"
    cached.mkdir(parents=True)
    victim = cached / "_version.py"
    victim.write_text(GENERATED_VERSION_MODULE, encoding="utf-8")

    version_bumper.bump_version_files("0.8.2", project_root=tmp_path)

    assert victim.read_text(encoding="utf-8") == GENERATED_VERSION_MODULE


def test_bump_skips_gitignored_directories(tmp_path):
    make_project(tmp_path)
    (tmp_path / ".gitignore").write_text("scratch/\n", encoding="utf-8")
    scratch = tmp_path / "scratch" / "vendored"
    scratch.mkdir(parents=True)
    victim = scratch / "_version.py"
    victim.write_text("__version__ = '3.2.1'\n", encoding="utf-8")

    version_bumper.bump_version_files("0.8.2", project_root=tmp_path)

    assert "3.2.1" in victim.read_text(encoding="utf-8")


def test_bump_refuses_a_build_generated_file_even_in_the_project_tree(tmp_path):
    """Fix 3 from the report: a "generated by" marker means someone else owns it."""
    make_project(tmp_path)
    generated = tmp_path / "demo" / "_version.py"
    generated.write_text(GENERATED_VERSION_MODULE, encoding="utf-8")

    bumped = version_bumper.bump_version_files("0.8.2", project_root=tmp_path)

    assert generated.read_text(encoding="utf-8") == GENERATED_VERSION_MODULE
    assert generated not in bumped


def test_bump_keeps_version_tuple_consistent(tmp_path):
    """Fix 5: never leave the string and the tuple describing different versions."""
    make_project(tmp_path)
    hand_written = tmp_path / "demo" / "_version.py"
    hand_written.write_text(
        "__version__ = version = '0.1.0'\n__version_tuple__ = version_tuple = (0, 1, 0)\n",
        encoding="utf-8",
    )

    version_bumper.bump_version_files("0.8.2", project_root=tmp_path)

    text = hand_written.read_text(encoding="utf-8")
    assert "__version__ = version = '0.8.2'" in text
    assert "version_tuple = (0, 8, 2)" in text
    assert "(0, 1, 0)" not in text


def test_bare_version_assignment_is_only_honored_in_setup_py(tmp_path):
    """The over-broad ``version = "..."`` match is what hit generated modules."""
    module = tmp_path / "_version.py"
    module.write_text("version = '9.1.1'\n", encoding="utf-8")
    assert update.update_python_file(module, "0.8.2") is False
    assert "9.1.1" in module.read_text(encoding="utf-8")

    setup = tmp_path / "setup.py"
    setup.write_text("setup(\n)\nversion = '9.1.1'\n", encoding="utf-8")
    assert update.update_python_file(setup, "0.8.2") is True
    assert "0.8.2" in setup.read_text(encoding="utf-8")


def test_plan_version_files_enumerates_only_project_files(tmp_path):
    """Fix 4: the dry run must be able to list its targets."""
    pkg = make_project(tmp_path)
    make_site_packages(tmp_path / ".venv")

    candidates = version_bumper.plan_version_files(project_root=tmp_path)

    assert set(candidates) == {tmp_path / "pyproject.toml", pkg / "__init__.py"}


def test_find_source_files_can_opt_out_of_gitignore(tmp_path):
    """Hard excludes still apply when .gitignore handling is disabled."""
    make_project(tmp_path)
    (tmp_path / ".gitignore").write_text("scratch/\n", encoding="utf-8")
    scratch = tmp_path / "scratch"
    scratch.mkdir()
    (scratch / "_version.py").write_text("__version__ = '1'\n", encoding="utf-8")
    victim = make_site_packages(tmp_path / ".venv")

    found = set(jiggle_version.find_source_files(tmp_path, use_gitignore=False))

    assert scratch / "_version.py" in found
    assert victim not in found
