# SPDX-License-Identifier: Apache-2.0; see LICENSE.md.

"""Commit-message linting against the Keep a Changelog commit schema.

This is the shared core behind the ``commit-msg`` pre-commit hook, the
``lint-commits`` audit command, and the ``rewrite-messages`` history rewriter.
It classifies a commit *subject* into one of three outcomes:

* :attr:`LintOutcome.CHANGELOG` - the subject declares a valid Keep a Changelog
  change type via a recognized schema prefix (``Added: ...``, ``feat: ...``,
  ``🐛 ...``) and would become a real changelog entry on backfill.
* :attr:`LintOutcome.SKIP` - the subject is a recognized *non-changelog* commit
  (``chore:``, ``docs:``, ``refactor:`` ...). Valid, intentionally excluded.
* :attr:`LintOutcome.UNCLASSIFIED` - the subject matched nothing, or used a
  ``Word:`` prefix whose ``Word`` is neither a Keep a Changelog category nor a
  known skip-type. Backfill would turn this into a bogus low-confidence
  ``changed`` entry, so the linter rejects it.

The classifier deliberately reuses the parser registry in
:mod:`changelogmanager.backfill` and the categories in
:mod:`changelogmanager.change_types`, so "lint passes" stays in lockstep with
"backfill can classify it". See ``spec/message_linting.md``.
"""

from __future__ import annotations

import re
import subprocess  # nosec
from dataclasses import dataclass, field
from enum import Enum

import changelogmanager.llvm_diagnostics as logging
from changelogmanager import backfill
from changelogmanager.backfill import (
    CONVENTIONAL_RE,
    CONVENTIONAL_TO_KAC,
    MAX_COMMITS_DEFAULT,
    git_executable,
)
from changelogmanager.change_types import TYPES_OF_CHANGE
from changelogmanager.runtime_logging import get_logger

logger = get_logger(__name__)

#: Conventional types whose KAC mapping is the "skip" sentinel (``None``). These
#: are recognized as intentionally non-changelog commits regardless of the
#: selected schema, so a ``chore:``/``docs:`` commit always passes the lint.
SKIP_TYPES: frozenset[str] = frozenset(
    name for name, kac in CONVENTIONAL_TO_KAC.items() if kac is None
)

#: Subjects that are never linted (merges, reverts, fixups, autogenerated bumps).
#: Matched case-insensitively as a prefix anchor.
DEFAULT_EXEMPT_PATTERNS: tuple[str, ...] = (
    r"^Merge ",
    r"^Revert ",
    r"^fixup! ",
    r"^squash! ",
    r"^Bump version",
)


class LintOutcome(Enum):
    """Classification of a commit subject for changelog purposes."""

    CHANGELOG = "changelog"
    SKIP = "skip"
    UNCLASSIFIED = "unclassified"


@dataclass(frozen=True)
class LintResult:
    """The outcome of linting a single commit subject."""

    subject: str
    outcome: LintOutcome
    change_type: str | None = None
    matched_schema: str | None = None
    reason: str = ""

    @property
    def ok(self) -> bool:
        """True when the subject passes the lint (changelog, skip, or exempt)."""

        return self.outcome is not LintOutcome.UNCLASSIFIED


@dataclass(frozen=True)
class LintOptions:
    """Resolved knobs controlling :func:`classify_subject`.

    Mirrors the ``[tool.changelogmanager.validation.message_lint]`` config table;
    :func:`changelogmanager.config.get_message_lint_options` builds one of these.
    """

    enabled: bool = False
    schema: str = "auto"
    allow_unknown_conventional_types: bool = False
    allow_skip_types: bool = True
    exempt_patterns: tuple[str, ...] = DEFAULT_EXEMPT_PATTERNS
    _exempt_compiled: tuple[re.Pattern[str], ...] = field(
        default=(), repr=False, compare=False
    )

    def compiled_exempt(self) -> tuple[re.Pattern[str], ...]:
        """Returns compiled exempt patterns, compiling lazily on first use."""

        if self._exempt_compiled:
            return self._exempt_compiled
        compiled = tuple(
            re.compile(pattern, re.IGNORECASE) for pattern in self.exempt_patterns
        )
        # frozen dataclass: stash via object.__setattr__ to memoize.
        object.__setattr__(self, "_exempt_compiled", compiled)
        return compiled


_VALID_CATEGORIES = ", ".join(name.capitalize() + ":" for name in TYPES_OF_CHANGE)
_UNCLASSIFIED_HINT = (
    f"prefix with a Keep a Changelog category ({_VALID_CATEGORIES}) "
    "or a Conventional type (feat:, fix:, ... or chore:/docs:/refactor: "
    "to intentionally skip)"
)


def subject_of(message: str) -> str:
    """Extracts the subject line from a full commit message.

    The subject is the first non-blank, non-comment line. ``commit-msg`` files
    contain comment lines (``# ...``) and a possibly blank leading line; this
    mirrors how git itself derives ``%s``.
    """

    for raw_line in message.splitlines():
        line = raw_line.rstrip()
        if not line.strip():
            continue
        if line.lstrip().startswith("#"):
            continue
        return line
    return ""


def _conventional_type(subject: str) -> str | None:
    """Returns the lowercased Conventional type prefix, or None when absent."""

    match = CONVENTIONAL_RE.match(subject)
    if not match:
        return None
    return match.group("type").lower()


def is_exempt(subject: str, options: LintOptions) -> bool:
    """True when the subject matches a configured exempt pattern."""

    return any(pattern.search(subject) for pattern in options.compiled_exempt())


def classify_subject(
    subject: str,
    *,
    schema: str = "auto",
    options: LintOptions | None = None,
) -> LintResult:
    """Classifies a commit subject for changelog purposes.

    ``schema`` selects the commit-message schema (``auto`` / ``conventional`` /
    ``gitmoji`` / ``keepachangelog``); when ``options`` is given its ``schema``
    is used and ``schema`` is ignored. The decision tree:

    1. Exempt patterns (merges etc.) short-circuit to :attr:`LintOutcome.SKIP`.
    2. A recognized Conventional *skip* type (``chore:``, ``docs:`` ...) yields
       :attr:`LintOutcome.SKIP` regardless of the selected schema, so teams that
       mix in non-changelog commits are never punished.
    3. Otherwise the backfill parser registry is consulted: a hit is
       :attr:`LintOutcome.CHANGELOG`; a miss is :attr:`LintOutcome.UNCLASSIFIED`.
    4. An unknown Conventional type (``Frobnicate: ...``) is escalated to
       :attr:`LintOutcome.UNCLASSIFIED` unless
       ``allow_unknown_conventional_types`` is set, matching backfill's lenient
       "unknown type -> changed" default.
    """

    opts = options or LintOptions(schema=schema)
    effective_schema = opts.schema
    subject = subject.strip()

    if not subject:
        return LintResult(
            subject=subject,
            outcome=LintOutcome.UNCLASSIFIED,
            reason="empty commit subject",
        )

    if is_exempt(subject, opts):
        return LintResult(
            subject=subject,
            outcome=LintOutcome.SKIP,
            matched_schema="exempt",
            reason="matched an exempt pattern (merge/revert/fixup/bump)",
        )

    # Step 2: skip-types are recognized irrespective of the selected schema.
    conv_type = _conventional_type(subject)
    if conv_type in SKIP_TYPES:
        if opts.allow_skip_types:
            return LintResult(
                subject=subject,
                outcome=LintOutcome.SKIP,
                matched_schema="conventional",
                reason=f"'{conv_type}:' is a recognized non-changelog commit type",
            )
        return LintResult(
            subject=subject,
            outcome=LintOutcome.UNCLASSIFIED,
            reason=(
                f"'{conv_type}:' is a non-changelog type but skip types are "
                "disabled (allow_skip_types = false)"
            ),
        )

    # Step 3: defer to the backfill parser registry for the real classification.
    parsed = backfill.classify_commit_subject(subject, schema=effective_schema)
    if parsed is not None:
        change_type, _ = parsed
        # Step 4: catch unknown Conventional types that only classified because
        # backfill defaults unknown types to "changed".
        if (
            not opts.allow_unknown_conventional_types
            and conv_type is not None
            and conv_type not in CONVENTIONAL_TO_KAC
            and effective_schema in {"auto", "conventional"}
        ):
            return LintResult(
                subject=subject,
                outcome=LintOutcome.UNCLASSIFIED,
                reason=(
                    f"'{conv_type}:' is not a known Conventional type; it would "
                    "be backfilled as a generic 'changed' entry. Use a real type "
                    "or a Keep a Changelog category"
                ),
            )
        return LintResult(
            subject=subject,
            outcome=LintOutcome.CHANGELOG,
            change_type=change_type,
            matched_schema=effective_schema,
            reason=f"classified as '{change_type}'",
        )

    return LintResult(
        subject=subject,
        outcome=LintOutcome.UNCLASSIFIED,
        reason=_UNCLASSIFIED_HINT,
    )


# ----------------------------------------------------------------------
# Audit: classify a range of past commits (the `lint-commits` command)
# ----------------------------------------------------------------------


@dataclass(frozen=True)
class CommitLint:
    """A single commit's classification in an audit run."""

    sha: str
    subject: str
    result: LintResult

    def to_json(self) -> dict[str, object]:
        return {
            "sha": self.sha,
            "subject": self.subject,
            "outcome": self.result.outcome.value,
            "change_type": self.result.change_type,
            "matched_schema": self.result.matched_schema,
            "reason": self.result.reason,
        }


@dataclass(frozen=True)
class AuditReport:
    """The result of linting a range of commits."""

    commits: list[CommitLint]
    revision: str

    @property
    def counts(self) -> dict[str, int]:
        """Per-outcome commit counts (changelog/skip/unclassified)."""

        tally = {outcome.value: 0 for outcome in LintOutcome}
        for commit in self.commits:
            tally[commit.result.outcome.value] += 1
        return tally

    @property
    def unclassified(self) -> list[CommitLint]:
        """Commits whose subject failed the lint."""

        return [
            commit
            for commit in self.commits
            if commit.result.outcome is LintOutcome.UNCLASSIFIED
        ]

    def to_json(self) -> dict[str, object]:
        return {
            "revision": self.revision,
            "counts": self.counts,
            "commits": [commit.to_json() for commit in self.commits],
        }


def audit_commits(
    *,
    since: str | None = None,
    until: str | None = None,
    cwd: str | None = None,
    options: LintOptions | None = None,
    max_commits: int = MAX_COMMITS_DEFAULT,
) -> AuditReport:
    """Lints every non-merge commit in a range and returns a classification report.

    The walk reuses :mod:`changelogmanager.backfill`'s git helpers and runaway
    guard, so the budget and ``--no-merges`` behaviour match what backfill would
    actually ingest. ``since``/``until`` bound the range; when ``until`` is
    ``None`` the walk runs to ``HEAD``. A ``None`` ``since`` walks from the
    repository root (callers default it to the last tag for parity with
    ``from-commits``).
    """

    opts = options or LintOptions()
    start = until or "HEAD"
    revision = f"{since}..{start}" if since else start

    # Cheap pre-flight: refuse monster ranges before materializing commits.
    backfill.enforce_commit_budget(revision, max_commits=max_commits, cwd=cwd)

    commits = backfill.git_log_between(since, start, cwd=cwd)
    linted = [
        CommitLint(
            sha=commit.sha,
            subject=commit.subject,
            result=classify_subject(commit.subject, options=opts),
        )
        for commit in commits
    ]
    logger.info(
        "Audited %d commit(s) in %s: %s",
        len(linted),
        revision,
        AuditReport(commits=linted, revision=revision).counts,
    )
    return AuditReport(commits=linted, revision=revision)


# ----------------------------------------------------------------------
# Unpushed-range resolution (the only range `rewrite-messages` may touch)
# ----------------------------------------------------------------------


@dataclass(frozen=True)
class UnpushedRange:
    """The local-only commit range that is safe to rewrite.

    ``revision`` is a git range expression (``<base>..HEAD``) when an upstream
    exists, or ``HEAD`` when the branch has no upstream at all (a brand-new local
    branch whose commits have never been pushed). ``has_upstream`` distinguishes
    the two so callers can explain the scope.
    """

    revision: str
    has_upstream: bool
    upstream: str | None


def _git(args: list[str], *, cwd: str | None) -> subprocess.CompletedProcess[str]:
    return subprocess.run(  # nosec B603
        [git_executable(), *args],
        capture_output=True,
        text=True,
        cwd=cwd,
        check=False,
    )


def resolve_unpushed_range(*, cwd: str | None = None) -> UnpushedRange:
    """Resolves the unpushed commit range for the current branch.

    Prefers ``@{push}`` (the branch commits are pushed *to*), then
    ``@{upstream}``. When neither is configured the branch has no upstream and
    *all* of its commits are local-only, so the range is ``HEAD``.

    This is the **only** range ``rewrite-messages`` is ever allowed to operate
    on: every commit it returns is provably not present on any remote-tracking
    branch, so a rewrite can never corrupt pushed history.
    """

    # Confirm we are in a git work tree first for a clean error.
    inside = _git(["rev-parse", "--is-inside-work-tree"], cwd=cwd)
    if inside.returncode != 0 or inside.stdout.strip() != "true":
        raise logging.Error(
            message="rewrite-messages must be run inside a git working tree"
        )

    for ref in ("@{push}", "@{upstream}"):
        resolved = _git(["rev-parse", "--verify", "--quiet", ref], cwd=cwd)
        if resolved.returncode == 0 and resolved.stdout.strip():
            logger.info("Unpushed range bounded by %s", ref)
            return UnpushedRange(
                revision=f"{ref}..HEAD", has_upstream=True, upstream=ref
            )

    logger.info("No upstream configured; treating all of HEAD as local-only")
    return UnpushedRange(revision="HEAD", has_upstream=False, upstream=None)


# ----------------------------------------------------------------------
# Rewrite planning (the `rewrite-messages` command; plan-only for now)
# ----------------------------------------------------------------------

#: Keyword → KAC category hints used when guessing a category for an
#: unclassified subject. First match wins; order matters (most specific first).
_CATEGORY_KEYWORDS: tuple[tuple[str, str], ...] = (
    ("secur", "security"),
    ("vuln", "security"),
    ("cve", "security"),
    ("deprecat", "deprecated"),
    ("remov", "removed"),
    ("delet", "removed"),
    ("drop", "removed"),
    ("fix", "fixed"),
    ("bug", "fixed"),
    ("patch", "fixed"),
    ("repair", "fixed"),
    ("add", "added"),
    ("introduc", "added"),
    ("new ", "added"),
    ("implement", "added"),
    ("support", "added"),
)


def guess_category(subject: str) -> str:
    """Guesses a KAC category from keywords in a subject, defaulting to changed."""

    lowered = subject.lower()
    for keyword, category in _CATEGORY_KEYWORDS:
        if keyword in lowered:
            return category
    return "changed"


def suggest_subject(subject: str, *, auto_prefix: str | None = None) -> str:
    """Proposes a rewritten subject that classifies as a KAC change.

    ``auto_prefix`` forces a specific category prefix (e.g. ``changed``); when
    ``None`` a category is guessed from the subject's keywords. The original
    text is preserved as the body of the new subject.
    """

    category = auto_prefix or guess_category(subject)
    title = category.capitalize()
    return f"{title}: {subject.strip()}"


@dataclass(frozen=True)
class RewriteEntry:
    """A single proposed subject rewrite for one unpushed commit."""

    sha: str
    old_subject: str
    suggested_subject: str
    outcome_after: str

    def to_json(self) -> dict[str, str]:
        return {
            "sha": self.sha,
            "old_subject": self.old_subject,
            "suggested_subject": self.suggested_subject,
            "outcome_after": self.outcome_after,
        }

    def to_tsv(self) -> str:
        # Tabs separate fields; strip any stray tabs/newlines from subjects so a
        # record stays on one line and round-trips cleanly.
        def clean(text: str) -> str:
            return text.replace("\t", " ").replace("\n", " ").strip()

        return "\t".join(
            (
                self.sha,
                clean(self.old_subject),
                clean(self.suggested_subject),
                self.outcome_after,
            )
        )


@dataclass(frozen=True)
class RewritePlan:
    """A plan of proposed rewrites over the unpushed commit range."""

    unpushed_range: str
    has_upstream: bool
    entries: list[RewriteEntry]
    audit: AuditReport

    @property
    def still_unclassified(self) -> list[RewriteEntry]:
        """Proposed rewrites whose suggestion still does not classify."""

        return [
            entry
            for entry in self.entries
            if entry.outcome_after == LintOutcome.UNCLASSIFIED.value
        ]

    def to_tsv(self) -> str:
        return "\n".join(entry.to_tsv() for entry in self.entries)

    def to_json(self) -> dict[str, object]:
        return {
            "unpushed_range": self.unpushed_range,
            "has_upstream": self.has_upstream,
            "counts": self.audit.counts,
            "entries": [entry.to_json() for entry in self.entries],
        }


def plan_rewrite(
    *,
    cwd: str | None = None,
    options: LintOptions | None = None,
    auto_prefix: str | None = None,
    max_commits: int = MAX_COMMITS_DEFAULT,
) -> RewritePlan:
    """Builds a rewrite plan over the unpushed range. **Touches no history.**

    Audits the unpushed commits, and for each non-exempt ``UNCLASSIFIED`` commit
    proposes a rewritten subject (re-linted so ``outcome_after`` reflects whether
    the suggestion actually classifies). The returned plan is the artifact a
    human/agent reviews and edits before any (future) apply step.
    """

    opts = options or LintOptions()
    unpushed = resolve_unpushed_range(cwd=cwd)
    # unpushed.revision is either "<base>..HEAD" (upstream exists) or "HEAD"
    # (local-only branch). audit_commits builds the same shape from a `since`
    # base, so derive the base: the part before ".." or None for bare HEAD.
    base, sep, _ = unpushed.revision.partition("..")
    since = base if sep else None
    report = audit_commits(
        since=since,
        until=None,
        cwd=cwd,
        options=opts,
        max_commits=max_commits,
    )

    entries: list[RewriteEntry] = []
    for commit in report.unclassified:
        suggestion = suggest_subject(commit.subject, auto_prefix=auto_prefix)
        relinted = classify_subject(suggestion, options=opts)
        entries.append(
            RewriteEntry(
                sha=commit.sha,
                old_subject=commit.subject,
                suggested_subject=suggestion,
                outcome_after=relinted.outcome.value,
            )
        )

    logger.info(
        "Planned %d rewrite(s) over unpushed range %s",
        len(entries),
        unpushed.revision,
    )
    return RewritePlan(
        unpushed_range=unpushed.revision,
        has_upstream=unpushed.has_upstream,
        entries=entries,
        audit=report,
    )
