# SPDX-License-Identifier: Apache-2.0; see LICENSE.md.

"""Commit-message linting against the Keep a Changelog commit schema.

This is the shared core behind the ``commit-msg`` pre-commit hook, the
``lint-commits`` audit command, and the ``rewrite-messages`` history rewriter.
It classifies a commit *subject* into one of three outcomes:

* :attr:`LintOutcome.CHANGELOG` - the subject declares a valid Keep a Changelog
  change type via a recognized schema prefix (``Added: ...``, ``feat: ...``,
  ``🐛 ...``) and would become a real changelog entry on backfill.
* :attr:`LintOutcome.SKIP` - the subject is a recognized *non-changelog* commit
  (``chore:``, ``docs:``, ``refactor:`` ...). Valid, intentionally excluded.
* :attr:`LintOutcome.UNCLASSIFIED` - the subject matched nothing, or used a
  ``Word:`` prefix whose ``Word`` is neither a Keep a Changelog category nor a
  known skip-type. Backfill would turn this into a bogus low-confidence
  ``changed`` entry, so the linter rejects it.

The classifier deliberately reuses the parser registry in
:mod:`changelogmanager.backfill` and the categories in
:mod:`changelogmanager.change_types`, so "lint passes" stays in lockstep with
"backfill can classify it". See ``spec/message_linting.md``.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from enum import Enum

from changelogmanager import backfill
from changelogmanager.backfill import (
    CONVENTIONAL_RE,
    CONVENTIONAL_TO_KAC,
    MAX_COMMITS_DEFAULT,
)
from changelogmanager.change_types import TYPES_OF_CHANGE
from changelogmanager.runtime_logging import get_logger

logger = get_logger(__name__)

#: Conventional types whose KAC mapping is the "skip" sentinel (``None``). These
#: are recognized as intentionally non-changelog commits regardless of the
#: selected schema, so a ``chore:``/``docs:`` commit always passes the lint.
SKIP_TYPES: frozenset[str] = frozenset(
    name for name, kac in CONVENTIONAL_TO_KAC.items() if kac is None
)

#: Subjects that are never linted (merges, reverts, fixups, autogenerated bumps).
#: Matched case-insensitively as a prefix anchor.
DEFAULT_EXEMPT_PATTERNS: tuple[str, ...] = (
    r"^Merge ",
    r"^Revert ",
    r"^fixup! ",
    r"^squash! ",
    r"^Bump version",
)


class LintOutcome(Enum):
    """Classification of a commit subject for changelog purposes."""

    CHANGELOG = "changelog"
    SKIP = "skip"
    UNCLASSIFIED = "unclassified"


@dataclass(frozen=True)
class LintResult:
    """The outcome of linting a single commit subject."""

    subject: str
    outcome: LintOutcome
    change_type: str | None = None
    matched_schema: str | None = None
    reason: str = ""

    @property
    def ok(self) -> bool:
        """True when the subject passes the lint (changelog, skip, or exempt)."""

        return self.outcome is not LintOutcome.UNCLASSIFIED


@dataclass(frozen=True)
class LintOptions:
    """Resolved knobs controlling :func:`classify_subject`.

    Mirrors the ``[tool.changelogmanager.validation.message_lint]`` config table;
    :func:`changelogmanager.config.get_message_lint_options` builds one of these.
    """

    enabled: bool = False
    schema: str = "auto"
    allow_unknown_conventional_types: bool = False
    allow_skip_types: bool = True
    exempt_patterns: tuple[str, ...] = DEFAULT_EXEMPT_PATTERNS
    _exempt_compiled: tuple[re.Pattern[str], ...] = field(
        default=(), repr=False, compare=False
    )

    def compiled_exempt(self) -> tuple[re.Pattern[str], ...]:
        """Returns compiled exempt patterns, compiling lazily on first use."""

        if self._exempt_compiled:
            return self._exempt_compiled
        compiled = tuple(
            re.compile(pattern, re.IGNORECASE) for pattern in self.exempt_patterns
        )
        # frozen dataclass: stash via object.__setattr__ to memoize.
        object.__setattr__(self, "_exempt_compiled", compiled)
        return compiled


_VALID_CATEGORIES = ", ".join(
    name.capitalize() + ":" for name in TYPES_OF_CHANGE
)
_UNCLASSIFIED_HINT = (
    f"prefix with a Keep a Changelog category ({_VALID_CATEGORIES}) "
    "or a Conventional type (feat:, fix:, ... or chore:/docs:/refactor: "
    "to intentionally skip)"
)


def subject_of(message: str) -> str:
    """Extracts the subject line from a full commit message.

    The subject is the first non-blank, non-comment line. ``commit-msg`` files
    contain comment lines (``# ...``) and a possibly blank leading line; this
    mirrors how git itself derives ``%s``.
    """

    for raw_line in message.splitlines():
        line = raw_line.rstrip()
        if not line.strip():
            continue
        if line.lstrip().startswith("#"):
            continue
        return line
    return ""


def _conventional_type(subject: str) -> str | None:
    """Returns the lowercased Conventional type prefix, or None when absent."""

    match = CONVENTIONAL_RE.match(subject)
    if not match:
        return None
    return match.group("type").lower()


def is_exempt(subject: str, options: LintOptions) -> bool:
    """True when the subject matches a configured exempt pattern."""

    return any(pattern.search(subject) for pattern in options.compiled_exempt())


def classify_subject(
    subject: str,
    *,
    schema: str = "auto",
    options: LintOptions | None = None,
) -> LintResult:
    """Classifies a commit subject for changelog purposes.

    ``schema`` selects the commit-message schema (``auto`` / ``conventional`` /
    ``gitmoji`` / ``keepachangelog``); when ``options`` is given its ``schema``
    is used and ``schema`` is ignored. The decision tree:

    1. Exempt patterns (merges etc.) short-circuit to :attr:`LintOutcome.SKIP`.
    2. A recognized Conventional *skip* type (``chore:``, ``docs:`` ...) yields
       :attr:`LintOutcome.SKIP` regardless of the selected schema, so teams that
       mix in non-changelog commits are never punished.
    3. Otherwise the backfill parser registry is consulted: a hit is
       :attr:`LintOutcome.CHANGELOG`; a miss is :attr:`LintOutcome.UNCLASSIFIED`.
    4. An unknown Conventional type (``Frobnicate: ...``) is escalated to
       :attr:`LintOutcome.UNCLASSIFIED` unless
       ``allow_unknown_conventional_types`` is set, matching backfill's lenient
       "unknown type -> changed" default.
    """

    opts = options or LintOptions(schema=schema)
    effective_schema = opts.schema
    subject = subject.strip()

    if not subject:
        return LintResult(
            subject=subject,
            outcome=LintOutcome.UNCLASSIFIED,
            reason="empty commit subject",
        )

    if is_exempt(subject, opts):
        return LintResult(
            subject=subject,
            outcome=LintOutcome.SKIP,
            matched_schema="exempt",
            reason="matched an exempt pattern (merge/revert/fixup/bump)",
        )

    # Step 2: skip-types are recognized irrespective of the selected schema.
    conv_type = _conventional_type(subject)
    if conv_type in SKIP_TYPES:
        if opts.allow_skip_types:
            return LintResult(
                subject=subject,
                outcome=LintOutcome.SKIP,
                matched_schema="conventional",
                reason=f"'{conv_type}:' is a recognized non-changelog commit type",
            )
        return LintResult(
            subject=subject,
            outcome=LintOutcome.UNCLASSIFIED,
            reason=(
                f"'{conv_type}:' is a non-changelog type but skip types are "
                "disabled (allow_skip_types = false)"
            ),
        )

    # Step 3: defer to the backfill parser registry for the real classification.
    parsed = backfill.classify_commit_subject(subject, schema=effective_schema)
    if parsed is not None:
        change_type, _ = parsed
        # Step 4: catch unknown Conventional types that only classified because
        # backfill defaults unknown types to "changed".
        if (
            not opts.allow_unknown_conventional_types
            and conv_type is not None
            and conv_type not in CONVENTIONAL_TO_KAC
            and effective_schema in {"auto", "conventional"}
        ):
            return LintResult(
                subject=subject,
                outcome=LintOutcome.UNCLASSIFIED,
                reason=(
                    f"'{conv_type}:' is not a known Conventional type; it would "
                    "be backfilled as a generic 'changed' entry. Use a real type "
                    "or a Keep a Changelog category"
                ),
            )
        return LintResult(
            subject=subject,
            outcome=LintOutcome.CHANGELOG,
            change_type=change_type,
            matched_schema=effective_schema,
            reason=f"classified as '{change_type}'",
        )

    return LintResult(
        subject=subject,
        outcome=LintOutcome.UNCLASSIFIED,
        reason=_UNCLASSIFIED_HINT,
    )


# ----------------------------------------------------------------------
# Audit: classify a range of past commits (the `lint-commits` command)
# ----------------------------------------------------------------------


@dataclass(frozen=True)
class CommitLint:
    """A single commit's classification in an audit run."""

    sha: str
    subject: str
    result: LintResult

    def to_json(self) -> dict[str, object]:
        return {
            "sha": self.sha,
            "subject": self.subject,
            "outcome": self.result.outcome.value,
            "change_type": self.result.change_type,
            "matched_schema": self.result.matched_schema,
            "reason": self.result.reason,
        }


@dataclass(frozen=True)
class AuditReport:
    """The result of linting a range of commits."""

    commits: list[CommitLint]
    revision: str

    @property
    def counts(self) -> dict[str, int]:
        """Per-outcome commit counts (changelog/skip/unclassified)."""

        tally = {outcome.value: 0 for outcome in LintOutcome}
        for commit in self.commits:
            tally[commit.result.outcome.value] += 1
        return tally

    @property
    def unclassified(self) -> list[CommitLint]:
        """Commits whose subject failed the lint."""

        return [
            commit
            for commit in self.commits
            if commit.result.outcome is LintOutcome.UNCLASSIFIED
        ]

    def to_json(self) -> dict[str, object]:
        return {
            "revision": self.revision,
            "counts": self.counts,
            "commits": [commit.to_json() for commit in self.commits],
        }


def audit_commits(
    *,
    since: str | None = None,
    until: str | None = None,
    cwd: str | None = None,
    options: LintOptions | None = None,
    max_commits: int = MAX_COMMITS_DEFAULT,
) -> AuditReport:
    """Lints every non-merge commit in a range and returns a classification report.

    The walk reuses :mod:`changelogmanager.backfill`'s git helpers and runaway
    guard, so the budget and ``--no-merges`` behaviour match what backfill would
    actually ingest. ``since``/``until`` bound the range; when ``until`` is
    ``None`` the walk runs to ``HEAD``. A ``None`` ``since`` walks from the
    repository root (callers default it to the last tag for parity with
    ``from-commits``).
    """

    opts = options or LintOptions()
    start = until or "HEAD"
    revision = f"{since}..{start}" if since else start

    # Cheap pre-flight: refuse monster ranges before materializing commits.
    backfill.enforce_commit_budget(revision, max_commits=max_commits, cwd=cwd)

    commits = backfill.git_log_between(since, start, cwd=cwd)
    linted = [
        CommitLint(
            sha=commit.sha,
            subject=commit.subject,
            result=classify_subject(commit.subject, options=opts),
        )
        for commit in commits
    ]
    logger.info(
        "Audited %d commit(s) in %s: %s",
        len(linted),
        revision,
        AuditReport(commits=linted, revision=revision).counts,
    )
    return AuditReport(commits=linted, revision=revision)
